/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author jumag
 */
public class AdminLocal extends javax.swing.JFrame {

    /**
     * Creates new form AdminLocal
     */
    public AdminLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminLb = new javax.swing.JLabel();
        RegEmplBtn = new javax.swing.JButton();
        ElimEmplBtn = new javax.swing.JButton();
        UbiVehBtn = new javax.swing.JButton();
        HistVehBtn = new javax.swing.JButton();
        CerrSesiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(269, 300));

        AdminLb.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        AdminLb.setText("Administrador Local");

        RegEmplBtn.setBackground(new java.awt.Color(0, 0, 0));
        RegEmplBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegEmplBtn.setText("Registrar Empleado");
        RegEmplBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEmplBtnActionPerformed(evt);
            }
        });

        ElimEmplBtn.setBackground(new java.awt.Color(0, 0, 0));
        ElimEmplBtn.setForeground(new java.awt.Color(255, 255, 255));
        ElimEmplBtn.setText("Eliminar Empleado");
        ElimEmplBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimEmplBtnActionPerformed(evt);
            }
        });

        UbiVehBtn.setBackground(new java.awt.Color(0, 0, 0));
        UbiVehBtn.setForeground(new java.awt.Color(255, 255, 255));
        UbiVehBtn.setText("Ubicación Vehículo");
        UbiVehBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbiVehBtnActionPerformed(evt);
            }
        });

        HistVehBtn.setBackground(new java.awt.Color(0, 0, 0));
        HistVehBtn.setForeground(new java.awt.Color(255, 255, 255));
        HistVehBtn.setText("Historial Vehículo");
        HistVehBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistVehBtnActionPerformed(evt);
            }
        });

        CerrSesiBtn.setBackground(new java.awt.Color(0, 0, 0));
        CerrSesiBtn.setForeground(new java.awt.Color(255, 255, 255));
        CerrSesiBtn.setText("Cerrar Sesión");
        CerrSesiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrSesiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ElimEmplBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegEmplBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UbiVehBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HistVehBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CerrSesiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(AdminLb)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AdminLb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegEmplBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ElimEmplBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UbiVehBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HistVehBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CerrSesiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegEmplBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEmplBtnActionPerformed
        RegEmpl ventaRegEmpl = new RegEmpl();
        ventaRegEmpl.setVisible(true);
        ventaRegEmpl.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_RegEmplBtnActionPerformed

    private void ElimEmplBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimEmplBtnActionPerformed
        ElimEmpl ventaElimEmpl = new ElimEmpl();
        ventaElimEmpl.setVisible(true);
        ventaElimEmpl.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ElimEmplBtnActionPerformed

    private void UbiVehBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbiVehBtnActionPerformed
        UbiVehi ventaUbiVehi = new UbiVehi();
        ventaUbiVehi.setVisible(true);
        ventaUbiVehi.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_UbiVehBtnActionPerformed

    private void HistVehBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistVehBtnActionPerformed
        HistVehi ventaHistVehi = new HistVehi();
        ventaHistVehi.setVisible(true);
        ventaHistVehi.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_HistVehBtnActionPerformed

    private void CerrSesiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrSesiBtnActionPerformed
        MenuPrincipal ventaMenuPrinci = new MenuPrincipal();
        ventaMenuPrinci.setVisible(true);
        ventaMenuPrinci.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_CerrSesiBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLb;
    private javax.swing.JButton CerrSesiBtn;
    private javax.swing.JButton ElimEmplBtn;
    private javax.swing.JButton HistVehBtn;
    private javax.swing.JButton RegEmplBtn;
    private javax.swing.JButton UbiVehBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
