
package igu;

public class CliAppCli extends javax.swing.JFrame {

    public CliAppCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        CliLb = new javax.swing.JLabel();
        CreResBtn = new javax.swing.JButton();
        VehDisBtn = new javax.swing.JButton();
        CerrSesiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setPreferredSize(new java.awt.Dimension(269, 300));

        CliLb.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        CliLb.setText("Cliente");

        CreResBtn.setBackground(new java.awt.Color(0, 0, 0));
        CreResBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreResBtn.setText("Crear Reserva");
        CreResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreResBtnActionPerformed(evt);
            }
        });

        VehDisBtn.setBackground(new java.awt.Color(0, 0, 0));
        VehDisBtn.setForeground(new java.awt.Color(255, 255, 255));
        VehDisBtn.setText("Ver vehículos disponibles");
        VehDisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehDisBtnActionPerformed(evt);
            }
        });

        CerrSesiBtn.setBackground(new java.awt.Color(0, 0, 0));
        CerrSesiBtn.setForeground(new java.awt.Color(255, 255, 255));
        CerrSesiBtn.setText("Cerrar Sesión");
        CerrSesiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrSesiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VehDisBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreResBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CerrSesiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(CliLb)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CliLb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VehDisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CerrSesiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreResBtnActionPerformed
        CreResAppCli ventaCreResAppCli = new CreResAppCli();
        ventaCreResAppCli.setVisible(true);
        ventaCreResAppCli.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_CreResBtnActionPerformed

    private void VehDisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehDisBtnActionPerformed
        VehDis ventaVehDis = new VehDis();
        ventaVehDis.setVisible(true);
        ventaVehDis.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_VehDisBtnActionPerformed

    private void CerrSesiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrSesiBtnActionPerformed
        MenPriAppCli ventaMenPriAppCli = new MenPriAppCli();
        ventaMenPriAppCli.setVisible(true);
        ventaMenPriAppCli.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_CerrSesiBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrSesiBtn;
    private javax.swing.JLabel CliLb;
    private javax.swing.JLabel ClienteLb;
    private javax.swing.JLabel ClienteLb1;
    private javax.swing.JButton CreResBtn;
    private javax.swing.JButton CreaReseBtn;
    private javax.swing.JButton CreaReseBtn1;
    private javax.swing.JButton VehDisBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
