/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.io.File;
import javax.swing.*;
import logica.ImportarExportar;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jumag
 */
public class CreaAlqu extends javax.swing.JFrame {
    ImportarExportar modeloE = new ImportarExportar();
    DefaultTableModel nuevTabl;
    /**
     * Creates new form CreaAlqu
     */
    public CreaAlqu() {
        initComponents();
        nuevTabl=new DefaultTableModel();
        nuevTabl.addColumn("Id");
        nuevTabl.addColumn("Categoría");
        nuevTabl.addColumn("Fecha recogida");
        nuevTabl.addColumn("Ubicación recogida");
        nuevTabl.addColumn("Ubicación entrega");
        nuevTabl.addColumn("Fecha entrega temprano");
        nuevTabl.addColumn("Fecha entrega Tarde");
        nuevTabl.addColumn("Usuario cliente");
        nuevTabl.addColumn("Contraseña cliente");
        nuevTabl.addColumn("Conductores extra");
        nuevTabl.addColumn("Usuario del conductor");
        nuevTabl.addColumn("Contraseña del conductor");
        nuevTabl.addColumn("Reserva");
        llenarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreaAlquLb = new javax.swing.JLabel();
        CateLb = new javax.swing.JLabel();
        CateTf = new javax.swing.JTextField();
        FechRecLb = new javax.swing.JLabel();
        FecRecTf = new javax.swing.JTextField();
        UbiRecLb = new javax.swing.JLabel();
        UbiEntLb = new javax.swing.JLabel();
        FecEntTemTf = new javax.swing.JTextField();
        FecEntTarLb = new javax.swing.JLabel();
        FecEnTemLb = new javax.swing.JLabel();
        FecEntTarTf = new javax.swing.JTextField();
        CreAlquBtn = new javax.swing.JButton();
        UsuCliLb = new javax.swing.JLabel();
        ConCliLb = new javax.swing.JLabel();
        CondExLb = new javax.swing.JLabel();
        ConCondLb = new javax.swing.JLabel();
        UsuCondLb = new javax.swing.JLabel();
        UsuCliTf = new javax.swing.JTextField();
        CondExtTf = new javax.swing.JTextField();
        UsuCondTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        UbiRecJcb = new javax.swing.JComboBox<>();
        UbiEntJcb = new javax.swing.JComboBox<>();
        ConCliPf = new javax.swing.JPasswordField();
        ConCondPf = new javax.swing.JPasswordField();
        VolverBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreaAlquLb.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        CreaAlquLb.setText("Crear Alquiler");

        CateLb.setBackground(new java.awt.Color(255, 255, 255));
        CateLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CateLb.setText("Categoría:");

        FechRecLb.setBackground(new java.awt.Color(255, 255, 255));
        FechRecLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FechRecLb.setText("Fecha Recogida(DD/MM/AA):");

        UbiRecLb.setBackground(new java.awt.Color(255, 255, 255));
        UbiRecLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UbiRecLb.setText("Ubicación Recogida:");

        UbiEntLb.setBackground(new java.awt.Color(255, 255, 255));
        UbiEntLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UbiEntLb.setText("Ubicación Entrega:");

        FecEntTarLb.setBackground(new java.awt.Color(255, 255, 255));
        FecEntTarLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FecEntTarLb.setText("Fecha Entrega Tarde(DD/MM/AA):");

        FecEnTemLb.setBackground(new java.awt.Color(255, 255, 255));
        FecEnTemLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FecEnTemLb.setText("Fecha Entrega Temprano(DD/MM/AA):");

        CreAlquBtn.setBackground(new java.awt.Color(0, 0, 0));
        CreAlquBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreAlquBtn.setText("Crear Alquiler");
        CreAlquBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreAlquBtnActionPerformed(evt);
            }
        });

        UsuCliLb.setBackground(new java.awt.Color(255, 255, 255));
        UsuCliLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UsuCliLb.setText("Usuario Cliente:");

        ConCliLb.setBackground(new java.awt.Color(255, 255, 255));
        ConCliLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ConCliLb.setText("Contraseña Cliente:");

        CondExLb.setBackground(new java.awt.Color(255, 255, 255));
        CondExLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CondExLb.setText("Conductores extra:");

        ConCondLb.setBackground(new java.awt.Color(255, 255, 255));
        ConCondLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ConCondLb.setText("Contraseña del conductor:");

        UsuCondLb.setBackground(new java.awt.Color(255, 255, 255));
        UsuCondLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UsuCondLb.setText("Usuario del conductor:");

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtDatos);

        UbiRecJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir" }));

        UbiEntJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir" }));

        VolverBtn.setBackground(new java.awt.Color(0, 0, 0));
        VolverBtn.setForeground(new java.awt.Color(255, 255, 255));
        VolverBtn.setText("Volver");
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UbiEntLb)
                            .addComponent(CateLb)
                            .addComponent(FechRecLb)
                            .addComponent(UbiRecLb)
                            .addComponent(FecEnTemLb)
                            .addComponent(UsuCliLb)
                            .addComponent(ConCliLb)
                            .addComponent(CondExLb)
                            .addComponent(ConCondLb)
                            .addComponent(UsuCondLb)
                            .addComponent(FecEntTarLb))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FecEntTarTf)
                            .addComponent(FecEntTemTf)
                            .addComponent(UsuCliTf)
                            .addComponent(CondExtTf)
                            .addComponent(UsuCondTf)
                            .addComponent(UbiEntJcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConCliPf)
                            .addComponent(ConCondPf)
                            .addComponent(CateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FecRecTf)
                            .addComponent(UbiRecJcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CreAlquBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(VolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreaAlquLb)
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreaAlquLb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CateLb)
                    .addComponent(CateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechRecLb)
                    .addComponent(FecRecTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbiRecJcb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbiRecLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbiEntJcb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbiEntLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FecEntTemTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FecEnTemLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FecEntTarTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FecEntTarLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuCliTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuCliLb))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConCliPf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConCliLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CondExtTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CondExLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuCondLb)
                    .addComponent(UsuCondTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConCondLb)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ConCondPf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreAlquBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreAlquBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreAlquBtnActionPerformed
        String nombreArchivo = "Alquileres.xlsx";
        File archivo = new File(nombreArchivo);
        if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
            modeloE.Importar(archivo, jtDatos);
        } else {
            JOptionPane.showMessageDialog(null, "Elija un formato valido.");
        }
        String []info=new String[13];
        for (int i=0; i<jtDatos.getRowCount(); i++){
            String Id = String.valueOf(jtDatos.getValueAt(i, 0));
            String Cate = String.valueOf(jtDatos.getValueAt(i, 1));
            String FecRec = String.valueOf(jtDatos.getValueAt(i, 2));
            String UbiRec = String.valueOf(jtDatos.getValueAt(i, 3));
            String UbiEnt = String.valueOf(jtDatos.getValueAt(i, 4));
            String FecEntTemp = String.valueOf(jtDatos.getValueAt(i, 5));
            String FecEntTar = String.valueOf(jtDatos.getValueAt(i, 6));
            String UsuCli = String.valueOf(jtDatos.getValueAt(i, 7));
            String ConCli = String.valueOf(jtDatos.getValueAt(i, 8));
            String CondEx = String.valueOf(jtDatos.getValueAt(i, 9));
            String UsuCond = String.valueOf(jtDatos.getValueAt(i, 10));
            String ConCond = String.valueOf(jtDatos.getValueAt(i, 11));
            String Reserva = String.valueOf(jtDatos.getValueAt(i, 12));
            info[0]= Id;
            info[1]= Cate;
            info[2]= FecRec;
            info[3]= UbiRec;
            info[4]= UbiEnt;
            info[5]= FecEntTemp;
            info[6]= FecEntTar;
            info[7]= UsuCli;
            info[8]= ConCli;
            info[9]= CondEx;
            info[10]= UsuCond;
            info[11]= ConCond;
            info[12]= Reserva;
            nuevTabl.addRow(info);
        }
        info[0]= String.valueOf(nuevTabl.getRowCount()+1);
        info[1]= CateTf.getText();
        info[2]= FecRecTf.getText();
        info[3]= UbiRecJcb.getSelectedItem().toString();
        info[4]= UbiEntJcb.getSelectedItem().toString();
        info[5]= FecEntTemTf.getText();
        info[6]= FecEntTarTf.getText();
        info[7]= UsuCliTf.getText();
        info[8]= ConCliPf.getText();
        info[9]= CondExtTf.getText();
        info[10]= UsuCondTf.getText();
        info[11]= ConCondPf.getText();
        info[12]= "No";
        nuevTabl.addRow(info);
        this.jtDatos.setModel(nuevTabl);
        if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
            modeloE.Exportar(archivo, jtDatos);
        } else {
            JOptionPane.showMessageDialog(null, "Elija un formato valido.");
        }
        JOptionPane.showMessageDialog(null, "Ha agregado un alquiler al sistema.");
        Empleado ventaEmpl = new Empleado();
        ventaEmpl.setVisible(true);
        ventaEmpl.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_CreAlquBtnActionPerformed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed
        Empleado ventaEmpl = new Empleado();
        ventaEmpl.setVisible(true);
        ventaEmpl.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_VolverBtnActionPerformed

    private void llenarComboBox() {
        String nombreArchivo = "Sedes.xlsx";
        File archivo = new File(nombreArchivo);
        if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
            modeloE.Importar(archivo, jtDatos);
        } else {
            JOptionPane.showMessageDialog(null, "Elija un formato valido.");
        }
        for (int i=0; i<jtDatos.getRowCount(); i++){
            UbiRecJcb.addItem(String.valueOf(jtDatos.getValueAt(i, 1)));
            UbiEntJcb.addItem(String.valueOf(jtDatos.getValueAt(i, 1)));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CateLb;
    private javax.swing.JTextField CateTf;
    private javax.swing.JLabel ConCliLb;
    private javax.swing.JPasswordField ConCliPf;
    private javax.swing.JLabel ConCondLb;
    private javax.swing.JPasswordField ConCondPf;
    private javax.swing.JLabel CondExLb;
    private javax.swing.JTextField CondExtTf;
    private javax.swing.JButton CreAlquBtn;
    private javax.swing.JLabel CreaAlquLb;
    private javax.swing.JLabel FecEnTemLb;
    private javax.swing.JLabel FecEntTarLb;
    private javax.swing.JTextField FecEntTarTf;
    private javax.swing.JTextField FecEntTemTf;
    private javax.swing.JTextField FecRecTf;
    private javax.swing.JLabel FechRecLb;
    private javax.swing.JComboBox<String> UbiEntJcb;
    private javax.swing.JLabel UbiEntLb;
    private javax.swing.JComboBox<String> UbiRecJcb;
    private javax.swing.JLabel UbiRecLb;
    private javax.swing.JLabel UsuCliLb;
    private javax.swing.JTextField UsuCliTf;
    private javax.swing.JLabel UsuCondLb;
    private javax.swing.JTextField UsuCondTf;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtDatos;
    // End of variables declaration//GEN-END:variables
}
