/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author jumag
 */
public class ModRese extends javax.swing.JFrame {

    /**
     * Creates new form ModRese
     */
    public ModRese() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ModResLb = new javax.swing.JLabel();
        IdResLb = new javax.swing.JLabel();
        IdResTf = new javax.swing.JTextField();
        FecRecLb = new javax.swing.JLabel();
        FecRecTf = new javax.swing.JTextField();
        UbiRecLb = new javax.swing.JLabel();
        UbiRecTf = new javax.swing.JTextField();
        FecEntTemLb = new javax.swing.JLabel();
        FecEntTemTf = new javax.swing.JTextField();
        FecEntTarTf = new javax.swing.JTextField();
        FecEntTarLb = new javax.swing.JLabel();
        ModResBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModResLb.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        ModResLb.setText("Modificar Reserva");

        IdResLb.setBackground(new java.awt.Color(255, 255, 255));
        IdResLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        IdResLb.setText("Id Reserva:");

        FecRecLb.setBackground(new java.awt.Color(255, 255, 255));
        FecRecLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FecRecLb.setText("Fecha Recogida:");

        UbiRecLb.setBackground(new java.awt.Color(255, 255, 255));
        UbiRecLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UbiRecLb.setText("Ubicación Recogida:");

        FecEntTemLb.setBackground(new java.awt.Color(255, 255, 255));
        FecEntTemLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FecEntTemLb.setText("Fecha Entrega Temprano:");

        FecEntTarLb.setBackground(new java.awt.Color(255, 255, 255));
        FecEntTarLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        FecEntTarLb.setText("Fecha Entrega tarde:");

        ModResBtn.setBackground(new java.awt.Color(0, 0, 0));
        ModResBtn.setForeground(new java.awt.Color(255, 255, 255));
        ModResBtn.setText("Modificar Reserva");
        ModResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModResBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ModResLb)
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FecEntTemLb)
                            .addComponent(IdResLb)
                            .addComponent(FecRecLb)
                            .addComponent(UbiRecLb)
                            .addComponent(FecEntTarLb))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FecRecTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdResTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UbiRecTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FecEntTemTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FecEntTarTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(ModResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ModResLb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IdResTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FecRecLb)
                            .addComponent(FecRecTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(IdResLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbiRecTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbiRecLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FecEntTemLb)
                    .addComponent(FecEntTemTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FecEntTarTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FecEntTarLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModResBtnActionPerformed

    }//GEN-LAST:event_ModResBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FecEntTarLb;
    private javax.swing.JTextField FecEntTarTf;
    private javax.swing.JLabel FecEntTemLb;
    private javax.swing.JTextField FecEntTemTf;
    private javax.swing.JLabel FecRecLb;
    private javax.swing.JTextField FecRecTf;
    private javax.swing.JLabel IdResLb;
    private javax.swing.JTextField IdResTf;
    private javax.swing.JButton ModResBtn;
    private javax.swing.JLabel ModResLb;
    private javax.swing.JLabel UbiRecLb;
    private javax.swing.JTextField UbiRecTf;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
