/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.io.File;
import javax.swing.*;
import logica.ImportarExportar;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jumag
 */
public class ModTarifa extends javax.swing.JFrame {
    ImportarExportar modeloE = new ImportarExportar();
    DefaultTableModel nuevTabl;
    /**
     * Creates new form ModTarifa
     */
    public ModTarifa() {
        initComponents();
        nuevTabl=new DefaultTableModel();
        nuevTabl.addColumn("Categoría Y Tipo");
        nuevTabl.addColumn("Tarifa diaria");
        nuevTabl.addColumn("Sede diferente");
        nuevTabl.addColumn("Seguro1");
        nuevTabl.addColumn("Seguro2");
        nuevTabl.addColumn("Conductor adicional");
        llenarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ModTarLb = new javax.swing.JLabel();
        CatYTipLb = new javax.swing.JLabel();
        UbiSedLb = new javax.swing.JLabel();
        HorApLb = new javax.swing.JLabel();
        Seg1Lb = new javax.swing.JLabel();
        TarDiaTf = new javax.swing.JTextField();
        SedDifTf = new javax.swing.JTextField();
        Seg1Tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        ModBtn = new javax.swing.JButton();
        VolverBtn = new javax.swing.JButton();
        Seg2Lb = new javax.swing.JLabel();
        Seg2Tf = new javax.swing.JTextField();
        ConAdiTf = new javax.swing.JTextField();
        ConAdiLb = new javax.swing.JLabel();
        CatYTipJcb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModTarLb.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        ModTarLb.setText("Modificar Tarifa");

        CatYTipLb.setBackground(new java.awt.Color(255, 255, 255));
        CatYTipLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CatYTipLb.setText("Categoría y Tipo:");

        UbiSedLb.setBackground(new java.awt.Color(255, 255, 255));
        UbiSedLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UbiSedLb.setText("Tarifa Diaria:");

        HorApLb.setBackground(new java.awt.Color(255, 255, 255));
        HorApLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        HorApLb.setText("Sede Diferente:");

        Seg1Lb.setBackground(new java.awt.Color(255, 255, 255));
        Seg1Lb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Seg1Lb.setText("Seguro 1:");

        TarDiaTf.setPreferredSize(new java.awt.Dimension(64, 30));

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtDatos);

        ModBtn.setBackground(new java.awt.Color(0, 0, 0));
        ModBtn.setForeground(new java.awt.Color(255, 255, 255));
        ModBtn.setText("Modificar");
        ModBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModBtnActionPerformed(evt);
            }
        });

        VolverBtn.setBackground(new java.awt.Color(0, 0, 0));
        VolverBtn.setForeground(new java.awt.Color(255, 255, 255));
        VolverBtn.setText("Volver");
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });

        Seg2Lb.setBackground(new java.awt.Color(255, 255, 255));
        Seg2Lb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Seg2Lb.setText("Seguro 2:");

        Seg2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seg2TfActionPerformed(evt);
            }
        });

        ConAdiTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConAdiTfActionPerformed(evt);
            }
        });

        ConAdiLb.setBackground(new java.awt.Color(255, 255, 255));
        ConAdiLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ConAdiLb.setText("Conductor Adicional:");

        CatYTipJcb.setPreferredSize(new java.awt.Dimension(64, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(ModTarLb))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(ModBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CatYTipLb)
                                    .addComponent(HorApLb)
                                    .addComponent(Seg1Lb)
                                    .addComponent(UbiSedLb)
                                    .addComponent(Seg2Lb)
                                    .addComponent(ConAdiLb))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SedDifTf)
                                    .addComponent(Seg1Tf)
                                    .addComponent(Seg2Tf)
                                    .addComponent(ConAdiTf)
                                    .addComponent(CatYTipJcb, 0, 155, Short.MAX_VALUE)
                                    .addComponent(TarDiaTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ModTarLb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatYTipJcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatYTipLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TarDiaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbiSedLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HorApLb)
                    .addComponent(SedDifTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seg1Lb)
                    .addComponent(Seg1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seg2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seg2Lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConAdiLb)
                    .addComponent(ConAdiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(323, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModBtnActionPerformed
        String nombreArchivo = "Tarifas.xlsx";
        File archivo = new File(nombreArchivo);
        modeloE.Importar(archivo, jtDatos);
        
        String []info=new String[6];
        for (int i=0; i<jtDatos.getRowCount(); i++){
            String CatYTip = String.valueOf(jtDatos.getValueAt(i, 0));
            String TarDia = String.valueOf(jtDatos.getValueAt(i, 1));
            String SedDif = String.valueOf(jtDatos.getValueAt(i, 2));
            String Seg1 = String.valueOf(jtDatos.getValueAt(i, 3));
            String Seg2 = String.valueOf(jtDatos.getValueAt(i, 4));
            String ConAdi = String.valueOf(jtDatos.getValueAt(i, 5));
            if (CatYTip.equals(CatYTipJcb.getSelectedItem().toString())){
                info[0]= CatYTip;
                info[1]= TarDiaTf.getText();
                info[2]= SedDifTf.getText();
                info[3]= Seg1Tf.getText();
                info[4]= Seg2Tf.getText();
                info[5]= ConAdiTf.getText();
            } else {
                info[0]= CatYTip;
                info[1]= TarDia;
                info[2]= SedDif;
                info[3]= Seg1;
                info[4]= Seg2;
                info[5]= ConAdi;
            }
            nuevTabl.addRow(info);
        }
        this.jtDatos.setModel(nuevTabl);
        modeloE.Exportar(archivo, jtDatos);
        JOptionPane.showMessageDialog(null, "Ha modificado la tarifa en el sistema.");
        AdminGeneral ventaAdminGen = new AdminGeneral();
        ventaAdminGen.setVisible(true);
        ventaAdminGen.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ModBtnActionPerformed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed
        AdminGeneral ventaAdminGen = new AdminGeneral();
        ventaAdminGen.setVisible(true);
        ventaAdminGen.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_VolverBtnActionPerformed

    private void Seg2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seg2TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seg2TfActionPerformed

    private void ConAdiTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConAdiTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConAdiTfActionPerformed

    private void llenarComboBox() {
        String nombreArchivo = "Tarifas.xlsx";
        File archivo = new File(nombreArchivo);
        modeloE.Importar(archivo, jtDatos);
        for (int i=0; i<jtDatos.getRowCount(); i++){
            CatYTipJcb.addItem(String.valueOf(jtDatos.getValueAt(i, 0)));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CatYTipJcb;
    private javax.swing.JLabel CatYTipLb;
    private javax.swing.JLabel ConAdiLb;
    private javax.swing.JTextField ConAdiTf;
    private javax.swing.JLabel HorApLb;
    private javax.swing.JButton ModBtn;
    private javax.swing.JLabel ModTarLb;
    private javax.swing.JTextField SedDifTf;
    private javax.swing.JLabel Seg1Lb;
    private javax.swing.JTextField Seg1Tf;
    private javax.swing.JLabel Seg2Lb;
    private javax.swing.JTextField Seg2Tf;
    private javax.swing.JTextField TarDiaTf;
    private javax.swing.JLabel UbiSedLb;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtDatos;
    // End of variables declaration//GEN-END:variables
}
