/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.io.File;
import javax.swing.JOptionPane;
import logica.ImportarExportar;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jumag
 */
public class RegAdmin extends javax.swing.JFrame {
    ImportarExportar modeloE = new ImportarExportar();
    DefaultTableModel nuevTabl;
    /**
     * Creates new form RegAdmin
     */
    public RegAdmin() {
        initComponents();
        nuevTabl=new DefaultTableModel();
        nuevTabl.addColumn("Usuario");
        nuevTabl.addColumn("Contraseña");
        nuevTabl.addColumn("Rol");
        nuevTabl.addColumn("Sede");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegAdmLb = new javax.swing.JLabel();
        NomUsuLb = new javax.swing.JLabel();
        ConLb = new javax.swing.JLabel();
        NumSedLb = new javax.swing.JLabel();
        UsuTf = new javax.swing.JTextField();
        RegAdmBtn = new javax.swing.JButton();
        NumSeTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        ConPf = new javax.swing.JPasswordField();
        RegAdmBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegAdmLb.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        RegAdmLb.setText("Registrar Administrador");

        NomUsuLb.setBackground(new java.awt.Color(255, 255, 255));
        NomUsuLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        NomUsuLb.setText("Nombre de usuario:");

        ConLb.setBackground(new java.awt.Color(255, 255, 255));
        ConLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ConLb.setText("Contraseña:");

        NumSedLb.setBackground(new java.awt.Color(255, 255, 255));
        NumSedLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        NumSedLb.setText("Número de sede:");

        RegAdmBtn.setBackground(new java.awt.Color(0, 0, 0));
        RegAdmBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegAdmBtn.setText("Registrar administrador");
        RegAdmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegAdmBtnActionPerformed(evt);
            }
        });

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtDatos);

        RegAdmBtn1.setBackground(new java.awt.Color(0, 0, 0));
        RegAdmBtn1.setForeground(new java.awt.Color(255, 255, 255));
        RegAdmBtn1.setText("Volver");
        RegAdmBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegAdmBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(RegAdmLb))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RegAdmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegAdmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomUsuLb, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConLb, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NumSedLb, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsuTf, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(NumSeTf)
                                    .addComponent(ConPf))))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(RegAdmLb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomUsuLb)
                    .addComponent(UsuTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConPf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumSedLb)
                    .addComponent(NumSeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegAdmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegAdmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegAdmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegAdmBtnActionPerformed
        String nombreArchivo = "Datos.xlsx";
        File archivo = new File(nombreArchivo);
        if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
            modeloE.Importar(archivo, jtDatos);
        } else {
            JOptionPane.showMessageDialog(null, "Elija un formato valido.");
        }
        String []info=new String[4];
        for (int i=0; i<jtDatos.getRowCount(); i++){
            String Usuario = String.valueOf(jtDatos.getValueAt(i, 0));
            String Contraseña = String.valueOf(jtDatos.getValueAt(i, 1));
            String Rol = String.valueOf(jtDatos.getValueAt(i, 2));
            String Sede = String.valueOf(jtDatos.getValueAt(i, 3));
            info[0]=Usuario;
            info[1]=Contraseña;
            info[2]=Rol;
            info[3]=Sede;
            nuevTabl.addRow(info);
        }
        info[0]=UsuTf.getText();
        info[1]=ConPf.getText();
        info[2]="AdminLoc";
        info[3]=NumSeTf.getText();
        nuevTabl.addRow(info);
        this.jtDatos.setModel(nuevTabl);
        if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
            modeloE.Exportar(archivo, jtDatos);
        } else {
            JOptionPane.showMessageDialog(null, "Elija un formato valido.");
        }
        AdminGeneral ventaAdminGen = new AdminGeneral();
        ventaAdminGen.setVisible(true);
        ventaAdminGen.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_RegAdmBtnActionPerformed

    private void RegAdmBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegAdmBtn1ActionPerformed
        AdminGeneral ventaAdminGen = new AdminGeneral();
        ventaAdminGen.setVisible(true);
        ventaAdminGen.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_RegAdmBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConLb;
    private javax.swing.JPasswordField ConPf;
    private javax.swing.JLabel NomUsuLb;
    private javax.swing.JTextField NumSeTf;
    private javax.swing.JLabel NumSedLb;
    private javax.swing.JButton RegAdmBtn;
    private javax.swing.JButton RegAdmBtn1;
    private javax.swing.JLabel RegAdmLb;
    private javax.swing.JTextField UsuTf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtDatos;
    // End of variables declaration//GEN-END:variables
}
