
package igu;

import java.io.File;
import javax.swing.JOptionPane;
import logica.ImportarExportar;

public class UbiVehi extends javax.swing.JFrame {
    ImportarExportar modeloE = new ImportarExportar();
    String NumSede;

    public UbiVehi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BusUbiVehBtn = new javax.swing.JButton();
        PlaTf = new javax.swing.JTextField();
        PlaLb = new javax.swing.JLabel();
        UbiVehLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatos = new javax.swing.JTable();
        VolBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BusUbiVehBtn.setBackground(new java.awt.Color(0, 0, 0));
        BusUbiVehBtn.setForeground(new java.awt.Color(255, 255, 255));
        BusUbiVehBtn.setText("Buscar Ubicación del Vehículo");
        BusUbiVehBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusUbiVehBtnActionPerformed(evt);
            }
        });

        PlaLb.setBackground(new java.awt.Color(255, 255, 255));
        PlaLb.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        PlaLb.setText("Placa:");

        UbiVehLb.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        UbiVehLb.setText("Ubicación Vehículo ");

        jtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtDatos);

        VolBtn.setBackground(new java.awt.Color(0, 0, 0));
        VolBtn.setForeground(new java.awt.Color(255, 255, 255));
        VolBtn.setText("Volver");
        VolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BusUbiVehBtn)
                    .addComponent(UbiVehLb)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PlaLb)
                        .addGap(18, 18, 18)
                        .addComponent(PlaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VolBtn)
                        .addGap(56, 56, 56)))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(268, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(UbiVehLb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlaLb))
                .addGap(18, 18, 18)
                .addComponent(BusUbiVehBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VolBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusUbiVehBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusUbiVehBtnActionPerformed
        String nombreArchivo = "Vehiculos.xlsx";
        File archivo = new File(nombreArchivo);
        modeloE.Importar(archivo, jtDatos);
        for (int i=0; i<jtDatos.getRowCount(); i++){
            String Placa = String.valueOf(jtDatos.getValueAt(i, 0));
            String Numse = String.valueOf(jtDatos.getValueAt(i, 5));
            if (PlaTf.getText().equals(Placa)){
                NumSede = Numse;
            }
        }
        nombreArchivo = "Sedes.xlsx";
        archivo = new File(nombreArchivo);
        modeloE.Importar(archivo, jtDatos);
        boolean encontrado = false;
        for (int i=0; i<jtDatos.getRowCount(); i++){
            String Numero = String.valueOf(jtDatos.getValueAt(i, 0));
            String Nombre = String.valueOf(jtDatos.getValueAt(i, 1));
            if (Numero.equals(NumSede)){
                JOptionPane.showMessageDialog(null, "El vehiculo está en la sede "+Nombre);
                AdminGeneral ventaAdminGen = new AdminGeneral();
                ventaAdminGen.setVisible(true);
                ventaAdminGen.setLocationRelativeTo(null);
                this.setVisible(false);
                encontrado = true;
            }
        }
        if (!encontrado){
            JOptionPane.showMessageDialog(null, "El vehiculo no se ha encontrado");
            AdminGeneral ventaAdminGen = new AdminGeneral();
            ventaAdminGen.setVisible(true);
            ventaAdminGen.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BusUbiVehBtnActionPerformed

    private void VolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolBtnActionPerformed
        AdminGeneral ventaAdminGen = new AdminGeneral();
        ventaAdminGen.setVisible(true);
        ventaAdminGen.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_VolBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusUbiVehBtn;
    private javax.swing.JLabel PlaLb;
    private javax.swing.JTextField PlaTf;
    private javax.swing.JLabel UbiVehLb;
    private javax.swing.JButton VolBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtDatos;
    // End of variables declaration//GEN-END:variables
}
